### ISSUE TITLE
D: Make Bubble Burst Game responsive and increase the size of bubbles

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Amazing-Js-Projects#667] opened 2022-05-13 13:48 UTC
![image](https://user-images.githubusercontent.com/83345228/168295950-bb29acae-53e7-4be4-b966-5ff69905d87a.png)

**Comment by DEEPALI-SUK** [comment] 2022-05-21 04:48
@aaryahjolia ?

**Comment by Rishita489** [comment] 2022-05-21 20:13
Hey @arpit456jain , I am a GSSOC'22 contributor . If no one is working on this issue , can you assign it to me . I have solved the issue and send the PR . Can you please review and merge it .

**Comment by aaryahjolia** [comment] 2022-05-22 03:50
Hey @Rishita489 , Actually I'm working on the issue. But no worries you've made a PR. But from now please make a PR after the issue is assigned.

**Closed** 2022-05-22 19:18 UTC
Labels: enhancement, good first issue, GSSoC22
